  ## The name of the Docker Compose environment.
  name: majl2026-build-task-app
  services:
    # The UI service.
    ui:
      build:
        context: ./ui
        dockerfile: Dockerfile
      ports:
      # Make the UI available on http://localhost:3000
        - "3000:3000"
      # Tell the UI how to find your Spring Boot app.
      environment:
        - BACKEND_HOST=host.docker.internal
        - BACKEND_PORT=8806
      extra_hosts:
        - "host.docker.internal:host-gateway"